services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendso
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data:cached

  mailhog:
    build:
        context: .
        dockerfile: DockerFile-mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres: